In [1]:
import numpy as np

In [2]:
list1 =[1,2,3,4]

In [3]:
list1

[1, 2, 3, 4]

In [4]:
array = np.array(list1)

In [5]:
array     #1dimension

array([1, 2, 3, 4])

In [6]:
list2 = [[1,2,3,4],[5,6,7,8]]
list2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
array2d = np.array(list2)
array2d    #2dimension

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
array2d.shape

(2, 4)

In [9]:
array2d.dtype

dtype('int32')

In [10]:
list3 = [[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]
list3

[[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [5, 6, 7, 8]]]

In [11]:
array3d = np.array(list3)

In [12]:
array3d #3dimensional

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [13]:
array = np.array(list3)
array

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.random.rand(2)

array([0.83155454, 0.76049191])

In [19]:
np.random.rand(7)

array([0.07235684, 0.78786322, 0.40465913, 0.25174455, 0.05913824,
       0.48181831, 0.8702832 ])

In [20]:
?np.random.randint

In [21]:
?np.random

In [22]:
np.random.randint(5)

1

In [23]:
np.random.randint((1,5))

array([0, 2])

In [24]:
np.random.randint(1,5,2)

array([2, 3])

In [25]:
np.random.randint((1,10))

array([0, 9])

In [26]:
np.random.randint(1,100,4)

array([87, 73, 35, 13])

In [27]:
np.random.randint(1,10,(5,6))

array([[9, 7, 5, 9, 1, 7],
       [8, 8, 9, 2, 9, 2],
       [2, 7, 1, 1, 7, 2],
       [5, 7, 1, 5, 7, 5],
       [9, 7, 3, 3, 8, 5]])

In [28]:
np.arange(10,100,2) #size of 1 to 100 is 2 --10,12,14,etc..

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [29]:
np.arange(3,6,2)

array([3, 5])

In [30]:
np.linspace(1,100,2) #1 to 100 divide in 2 pats

array([  1., 100.])

In [31]:
np.linspace(1,100,50) #1 to 10 divide into 50 partd

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [32]:
?np.linspace

In [33]:
np.linspace(4,8,2)

array([4., 8.])

In [34]:
array = np.linspace(4,8,2)
array , array.shape

(array([4., 8.]), (2,))

In [35]:
np.eye(6) #identity matrix(digonals are 1 and every others arezero)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
np.eye(1)

array([[1.]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#reshaping

In [39]:
array5 = np.linspace(1,100,10)
array5 , array5.shape

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), (10,))

In [40]:
array5.reshape(5,2)

array([[  1.,  12.],
       [ 23.,  34.],
       [ 45.,  56.],
       [ 67.,  78.],
       [ 89., 100.]])

In [43]:
array5.reshape(2,5)

array([[  1.,  12.,  23.,  34.,  45.],
       [ 56.,  67.,  78.,  89., 100.]])

In [44]:
array5.reshape(3,2)

ValueError: cannot reshape array of size 10 into shape (3,2)