In [1]:
import numpy as np

In [2]:
array1 = np.random.rand(6,2)

In [3]:
array1

array([[0.12425169, 0.77280991],
       [0.91842963, 0.82596085],
       [0.82035832, 0.68856789],
       [0.53875295, 0.08661878],
       [0.08756891, 0.6406505 ],
       [0.40971021, 0.45268363]])

In [4]:
array2 = np.random.rand(6,2)
array2

array([[0.11070905, 0.96180563],
       [0.6332507 , 0.17565747],
       [0.29934037, 0.48871551],
       [0.03338107, 0.88435071],
       [0.26670007, 0.48643335],
       [0.55046022, 0.37738275]])

In [5]:
array_add =np.add(array1,array2)
array_add

array([[0.23496075, 1.73461553],
       [1.55168033, 1.00161832],
       [1.11969869, 1.1772834 ],
       [0.57213402, 0.97096949],
       [0.35426897, 1.12708385],
       [0.96017043, 0.83006638]])

In [6]:
array_add = np.subtract(array1,array2)

In [7]:
array_add

array([[ 0.01354264, -0.18899572],
       [ 0.28517894,  0.65030338],
       [ 0.52101794,  0.19985237],
       [ 0.50537188, -0.79773193],
       [-0.17913116,  0.15421714],
       [-0.14075001,  0.07530088]])

In [8]:
array_multi = np.multiply(array1,array2)
array_multi

array([[0.01375579, 0.74329292],
       [0.58159621, 0.14508619],
       [0.24556636, 0.33651381],
       [0.01798415, 0.07660138],
       [0.02335463, 0.31163377],
       [0.22552917, 0.17083499]])

In [9]:
#arrary_dot = dot proucr is the row of one matrix should
#match to the coloumn of the secnd matrix 
#here we have array1 (6,2) nd array2 also (6,2)
#hence we need to reshape array2 (2,6)


In [10]:
array3 = array2.reshape(2,6)

In [11]:
array3

array([[0.11070905, 0.96180563, 0.6332507 , 0.17565747, 0.29934037,
        0.48871551],
       [0.03338107, 0.88435071, 0.26670007, 0.48643335, 0.55046022,
        0.37738275]])

In [12]:
array_dot = np.dot(array1,array3)

In [13]:
array_dot

array([[0.03955301, 0.80294097, 0.28479093, 0.39774625, 0.46259466,
        0.35236886],
       [0.12924993, 1.61378985, 0.80188002, 0.56310393, 0.72958166,
        0.76055419],
       [0.11380622, 1.39796075, 0.70313358, 0.47904445, 0.6245956 ,
        0.66077548],
       [0.06253626, 0.594777  , 0.36426692, 0.13677024, 0.2089507 ,
        0.29598536],
       [0.03108027, 0.65078399, 0.2263146 , 0.3270159 , 0.37886552,
        0.28456673],
       [0.06046969, 0.79439267, 0.38018003, 0.29216908, 0.37182714,
        0.37106673]])

In [14]:
array_dot.shape

(6, 6)

In [15]:
#numpy broadcasting

In [16]:
array4 = array3 + 1

In [17]:
array4 

array([[1.11070905, 1.96180563, 1.6332507 , 1.17565747, 1.29934037,
        1.48871551],
       [1.03338107, 1.88435071, 1.26670007, 1.48643335, 1.55046022,
        1.37738275]])

In [18]:
x = np.array([1,2,3,4])
y = np.array([[1,2,3,4],[5,6,7,8]])
x.shape,y.shape,x,y,x+y
#numpy broadcasting - smaller array should be able o replicable in 
# the form of bigger matix

((4,),
 (2, 4),
 array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 2,  4,  6,  8],
        [ 6,  8, 10, 12]]))

In [19]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[1,2,3,4],[5,6,7,8]])
x.shape,y.shape,x,y,x+y

((2, 4),
 (2, 4),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16]]))

In [20]:
#ex 1. create a sequence of 20 numbers between 10 &40
#change the shape to a 2 dim matrix of 5,4
#square the matrix andmadd a quantity of 10to each element

In [21]:
array1 = np.linspace(14,40,20)
array2 = array1.reshape(5,4)
array3 = array2**2 +10

In [22]:
array1 , array2 , array3

(array([14.        , 15.36842105, 16.73684211, 18.10526316, 19.47368421,
        20.84210526, 22.21052632, 23.57894737, 24.94736842, 26.31578947,
        27.68421053, 29.05263158, 30.42105263, 31.78947368, 33.15789474,
        34.52631579, 35.89473684, 37.26315789, 38.63157895, 40.        ]),
 array([[14.        , 15.36842105, 16.73684211, 18.10526316],
        [19.47368421, 20.84210526, 22.21052632, 23.57894737],
        [24.94736842, 26.31578947, 27.68421053, 29.05263158],
        [30.42105263, 31.78947368, 33.15789474, 34.52631579],
        [35.89473684, 37.26315789, 38.63157895, 40.        ]]),
 array([[ 206.        ,  246.18836565,  290.12188366,  337.80055402],
        [ 389.22437673,  444.3933518 ,  503.30747922,  565.966759  ],
        [ 632.37119114,  702.52077562,  776.41551247,  854.05540166],
        [ 935.44044321, 1020.57063712, 1109.44598338, 1202.06648199],
        [1298.43213296, 1398.54293629, 1502.39889197, 1610.        ]]))

In [23]:
array1

array([14.        , 15.36842105, 16.73684211, 18.10526316, 19.47368421,
       20.84210526, 22.21052632, 23.57894737, 24.94736842, 26.31578947,
       27.68421053, 29.05263158, 30.42105263, 31.78947368, 33.15789474,
       34.52631579, 35.89473684, 37.26315789, 38.63157895, 40.        ])

In [24]:
array2

array([[14.        , 15.36842105, 16.73684211, 18.10526316],
       [19.47368421, 20.84210526, 22.21052632, 23.57894737],
       [24.94736842, 26.31578947, 27.68421053, 29.05263158],
       [30.42105263, 31.78947368, 33.15789474, 34.52631579],
       [35.89473684, 37.26315789, 38.63157895, 40.        ]])

In [25]:
array3

array([[ 206.        ,  246.18836565,  290.12188366,  337.80055402],
       [ 389.22437673,  444.3933518 ,  503.30747922,  565.966759  ],
       [ 632.37119114,  702.52077562,  776.41551247,  854.05540166],
       [ 935.44044321, 1020.57063712, 1109.44598338, 1202.06648199],
       [1298.43213296, 1398.54293629, 1502.39889197, 1610.        ]])

In [26]:
array3.sum() , array3.min() , array3.max(),array3.mean() ,array3.std()

(16025.263157894738, 206.0, 1610.0, 801.2631578947369, 429.69455498601957)

In [27]:
x = np.random.rand(3,4)
y = np.random.rand(3,4)
x,y,x>y

(array([[0.6103597 , 0.51513355, 0.44145469, 0.49095515],
        [0.53325206, 0.29129267, 0.79817309, 0.58577987],
        [0.60433327, 0.17217786, 0.21768791, 0.89594812]]),
 array([[0.17833701, 0.78109006, 0.92569523, 0.20355338],
        [0.36730935, 0.96424662, 0.18540083, 0.51334159],
        [0.07571241, 0.75630872, 0.26974203, 0.21166444]]),
 array([[ True, False, False,  True],
        [ True, False,  True,  True],
        [ True, False, False,  True]]))

In [28]:
x>0.5

array([[ True,  True, False, False],
       [ True, False,  True,  True],
       [ True, False, False,  True]])

In [29]:
x[x>0.5]

array([0.6103597 , 0.51513355, 0.53325206, 0.79817309, 0.58577987,
       0.60433327, 0.89594812])

In [30]:
x[1]

array([0.53325206, 0.29129267, 0.79817309, 0.58577987])

In [31]:
x[0]

array([0.6103597 , 0.51513355, 0.44145469, 0.49095515])

In [32]:
x[0][1]

0.5151335478129504

In [33]:
?np.append

In [34]:
z = np.append(x,y)
x,y,z.shape

(array([[0.6103597 , 0.51513355, 0.44145469, 0.49095515],
        [0.53325206, 0.29129267, 0.79817309, 0.58577987],
        [0.60433327, 0.17217786, 0.21768791, 0.89594812]]),
 array([[0.17833701, 0.78109006, 0.92569523, 0.20355338],
        [0.36730935, 0.96424662, 0.18540083, 0.51334159],
        [0.07571241, 0.75630872, 0.26974203, 0.21166444]]),
 (24,))

In [35]:
z = np.append(x,y,0)
x,y,z.shape
    

(array([[0.6103597 , 0.51513355, 0.44145469, 0.49095515],
        [0.53325206, 0.29129267, 0.79817309, 0.58577987],
        [0.60433327, 0.17217786, 0.21768791, 0.89594812]]),
 array([[0.17833701, 0.78109006, 0.92569523, 0.20355338],
        [0.36730935, 0.96424662, 0.18540083, 0.51334159],
        [0.07571241, 0.75630872, 0.26974203, 0.21166444]]),
 (6, 4))

In [36]:
z = np.append(x,y,1)
x,y,z.shape

(array([[0.6103597 , 0.51513355, 0.44145469, 0.49095515],
        [0.53325206, 0.29129267, 0.79817309, 0.58577987],
        [0.60433327, 0.17217786, 0.21768791, 0.89594812]]),
 array([[0.17833701, 0.78109006, 0.92569523, 0.20355338],
        [0.36730935, 0.96424662, 0.18540083, 0.51334159],
        [0.07571241, 0.75630872, 0.26974203, 0.21166444]]),
 (3, 8))

In [40]:
z = np.append(x,y)
x,z.shape

(array([[0.6103597 , 0.51513355, 0.44145469, 0.49095515],
        [0.53325206, 0.29129267, 0.79817309, 0.58577987],
        [0.60433327, 0.17217786, 0.21768791, 0.89594812]]),
 (24,))

In [42]:
?np.insert

In [45]:
np.insert(x,1,3) #here x is array nd 1 is the position where we add the numer nd 3 is the nu. which we added. 

array([0.6103597 , 3.        , 0.51513355, 0.44145469, 0.49095515,
       0.53325206, 0.29129267, 0.79817309, 0.58577987, 0.60433327,
       0.17217786, 0.21768791, 0.89594812])

In [44]:
np.insert(x,4,10) #here x is array nd 4 is the position where we add the numer nd 10 is the nu. which we added.

array([ 0.6103597 ,  0.51513355,  0.44145469,  0.49095515, 10.        ,
        0.53325206,  0.29129267,  0.79817309,  0.58577987,  0.60433327,
        0.17217786,  0.21768791,  0.89594812])

In [46]:
np.delete(x,1) #here we delete the 1th no. means 2nd position bo.

array([0.6103597 , 0.44145469, 0.49095515, 0.53325206, 0.29129267,
       0.79817309, 0.58577987, 0.60433327, 0.17217786, 0.21768791,
       0.89594812])

In [47]:
np.delete(x,0) #here we delete the 0th nu. means 1 position nu .

array([0.51513355, 0.44145469, 0.49095515, 0.53325206, 0.29129267,
       0.79817309, 0.58577987, 0.60433327, 0.17217786, 0.21768791,
       0.89594812])

In [50]:
x = np.random.rand(3,4)
x , np.reshape(5,4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [51]:
x = np.random.rand(3,4)
x , np.resize(x,(5,4))

(array([[0.77762934, 0.07367639, 0.18809355, 0.29756748],
        [0.75842715, 0.32749575, 0.48470411, 0.62128786],
        [0.71623005, 0.20787932, 0.16202844, 0.93731618]]),
 array([[0.77762934, 0.07367639, 0.18809355, 0.29756748],
        [0.75842715, 0.32749575, 0.48470411, 0.62128786],
        [0.71623005, 0.20787932, 0.16202844, 0.93731618],
        [0.77762934, 0.07367639, 0.18809355, 0.29756748],
        [0.75842715, 0.32749575, 0.48470411, 0.62128786]]))

In [58]:
x = np.random.rand(3,4)
x , np.resize(x,(5,4)),np.reshape(3,4)

ValueError: cannot reshape array of size 1 into shape (4,)